version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
max_jobs: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
notifications:
- provider: Email
  to:
  - robertknelson@gmail.com
  subject: 'Appveyor: eXtensoft-core'
  message: eXtensoft-core build occurred
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false

